apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: bh74788bm-go 
  janus-idp.io/tekton: bh74788bm-go
  backstage.io/kubernetes-id: bh74788bm-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bh74788bm-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  