apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: bh74788bm-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bh74788bm-go 
  name: bh74788bm-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: bh74788bm-go 
